#!/usr/bin/env groovy
pipeline {

    agent {
        node{
            label params.NODE_LABEL
        }
    }

    parameters {
        string(name: 'CREATED_YEAR', defaultValue: '2020', description: 'Filter in bugs created since this year')
        string(name: 'NODE_LABEL', defaultValue: '46', description: '')
        string(name: 'SCRIPTS_BRANCH', description: 'The wifi_drv-build_dev branch', defaultValue: 'master')
    }

    environment {
        BUILD_SYSTEM_MASTER_FOLDER = "$WORKSPACE/buildSystem"
        JIRA_BUGS_FOLDER = "$WORKSPACE/buildSystem/BuildScripts/jira_customer_tat"
        PYTHONIOENCODING = "utf-8"
    }

    options {
        skipDefaultCheckout false
        checkoutToSubdirectory('BuildScriptsForCleanup')
        timestamps()
        // script can be long depending on number of JIRA tickets
        timeout(time: 5, unit: 'HOURS')
    }

    stages {
        stage('Process Cleaner'){
            steps{
                script{
                    bat "python $WORKSPACE/BuildScriptsForCleanup/BuildScripts/process_cleaner.py"
                }
            }
        }
        stage('Clean Workspace'){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        stage('Pull FlowScripts') {
            steps{
                script{
                    dir(BUILD_SYSTEM_MASTER_FOLDER){
                        checkout scm
                    }
                }
            }
        }
        stage('Ensure Pip'){
            steps {
                withPythonEnv("python") {
                    dir("$JIRA_BUGS_FOLDER/") {
                        bat "python -m pip install --upgrade pip --proxy http://proxy-dmz.intel.com:912"
                        bat "python -m pip install -r requirements.txt --proxy http://proxy-dmz.intel.com:912"
                    }
                    dir("$BUILD_SYSTEM_MASTER_FOLDER/") {
                        bat "python -m pip install -r APIs/requirements.txt --proxy http://proxy-dmz.intel.com:912"
                    }
                }
            }
        }
        stage('JIRA Customer TAT') {
            steps{
                withPythonEnv("python") {
                    dir(BUILD_SYSTEM_MASTER_FOLDER){
                        bat ("python ${JIRA_BUGS_FOLDER}/jira_customer_tat.py"
                        + " --created-year ${CREATED_YEAR}")
                    }
                }
            }
        }
    }
}